version: '3.5'
services:
  workspace:
    build:
        context: ./
        args:
          - 'HOME=/workspace'
    volumes:
      - './workspace:/workspace:rw'
      - '${HOME}/.ssh:${HOME}/.ssh:rw'
      - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/passwd:/etc/passwd:ro'
      - '/etc/group:/etc/group:ro'
      - '/etc/shadow:/etc/shadow:ro'
      - '${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native'
      # - '~/contact-graspnet-DataGen:/contact-graspnet-DataGen'
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # - TIAGO_USER=${TIAGO_USER}
      # - TIAGO_UID=${TIAGO_UID}
      # - TIAGO_GID=${TIAGO_GID}
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - '/dev/snd'
    group_add:
      - 'audio'
    tty: true
    # entrypoint: "/entrypoint.sh"
    runtime: nvidia
    working_dir: '${HOME}'
    user: 1000:1000
    privileged: true
    network_mode: "host"
